# Generated by Django 5.0.6 on 2024-07-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemon', '0002_category_menuitem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='Category',
            new_name='category',
        ),
    ]
